/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_car_hardware_Mcu */

#ifndef _Included_com_car_hardware_Mcu
#define _Included_com_car_hardware_Mcu
#ifdef __cplusplus
extern "C" {
#endif
#undef com_car_hardware_Mcu_MCU_OPEN
#define com_car_hardware_Mcu_MCU_OPEN 1L
#undef com_car_hardware_Mcu_MCU_CLOSE
#define com_car_hardware_Mcu_MCU_CLOSE 2L
#undef com_car_hardware_Mcu_MCU_WRITE_DATA
#define com_car_hardware_Mcu_MCU_WRITE_DATA 3L
#undef com_car_hardware_Mcu_READ_KERNEL_PRO
#define com_car_hardware_Mcu_READ_KERNEL_PRO 4L
/*
 * Class:     com_car_hardware_Mcu
 * Method:    nativeSendCommand
 * Signature: (II[B)I
 */


#ifdef __cplusplus
}
#endif
#endif

